// <auto-generated />
using HiltonMovies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HiltonMovies.Migrations
{
    [DbContext(typeof(MovieDatabaseContext))]
    partial class MovieDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("HiltonMovies.Models.MovieModel", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Comedy",
                            Director = "Peter Farrelly",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Dumb and Dumber",
                            Year = 1994
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Sports",
                            Director = "Boaz Yakin",
                            Edited = false,
                            Rating = "PG",
                            Title = "Remember the Titans",
                            Year = 2000
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Comedy/Adventure",
                            Director = "Wes Anderson",
                            Edited = false,
                            Rating = "PG",
                            Title = "Fantastic Mr. Fox",
                            Year = 2009
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
